"""add_registry_columns

Revision ID: 726f1ece3679
Revises: 26be95c04c6c
Create Date: 2025-12-30 19:11:40.710446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '726f1ece3679'
down_revision: Union[str, Sequence[str], None] = '26be95c04c6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diagnostic_models', sa.Column('docker_image_path', sa.String(), nullable=True))
    op.add_column('diagnostic_models', sa.Column('model_weights_path', sa.String(), nullable=True))
    op.add_column('diagnostic_models', sa.Column('accuracy', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diagnostic_models', 'accuracy')
    op.drop_column('diagnostic_models', 'model_weights_path')
    op.drop_column('diagnostic_models', 'docker_image_path')
    # ### end Alembic commands ###
