"""encrypt_fhir_column

Revision ID: eca045ee9ce2
Revises: 726f1ece3679
Create Date: 2025-12-30 19:25:43.908844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import src.db.types

# revision identifiers, used by Alembic.
revision: str = 'eca045ee9ce2'
down_revision: Union[str, Sequence[str], None] = '726f1ece3679'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'fhir_bundle_input',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=src.db.types.EncryptedJSON(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'fhir_bundle_input',
               existing_type=src.db.types.EncryptedJSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    # ### end Alembic commands ###
